### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-api-core#210]
This would be semver major (`google-api-core` 2.0.0).  Clients which cannot move forward (e.g, `google-cloud-storage` already pin `google.api_core < 2.0.0dev` either directly or transitively (via `google-cloud-core`).

Extra cleanups:

- ~~Drop `mock` wrapper (use `from unittest import mock` directly, replacing work in #208).~~  Can't remove it until we drop support for Python 3.6 / 3.7, as it provides the `mock.AsyncMock` helper we need.
- [x] Drop `six`.
- [x] Drop other Python 2.7-specific workarounds (`collections_abc`, etc.)
- [x] Drop `u"` prefixes for text strings.
- [x] Drop `pytz` (per #73).
- ~~Replace [workaround](https://github.com/googleapis/python-api-core/blob/11032cf08ecc16dd252a6cda8b33b0b28ec4f4ba/google/api_core/bidi.py#L640-L652) in `bidi.BackgroundConsumer._thread_main` with `Condition.wait_for`.~~ Moved to #211.

**Comment by tseaver** [comment]
Extra cleanups:

- [ ] Drop `mock` wrapper (use `from unittest import mock` directly, replacing work in #208).
- [ ] Drop `six`.
- [ ] Drop `u"` prefixes for text strings.
- [ ] Drop `pytz` (per #73).
